/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.bapp.subscriptionbuddy;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.BufferedReader;
import java.io.FileReader;

        

/**
 *
 * @author Mustafa
 */
public class BuySubscriptionDialog extends javax.swing.JDialog {
    private static Subscription userData;
    private static String type = "";
    private static int price;

    /**
     * Creates new form BuySubscriptionDialog
     */
    public BuySubscriptionDialog(java.awt.Frame parent, boolean modal, Subscription userData,String type , int price) {
        super(parent, modal);
        initComponents();
        this.userData = userData;
        this.type = type;
        this.price = price;
        ErrorLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
        public List<String> readPurchaseHistory(String targetUsername) {
        List<String> purchaseRecords = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader("purchase.txt"))) {
            String line;
            boolean found = false;

            while ((line = br.readLine()) != null) {
                String username = line;
                String subscription = br.readLine();
                String price = br.readLine();

                if (username == null || subscription == null || price == null) {
                    System.out.println("Invalid record found in the file.");
                    continue;
                }

                if (username.equals(targetUsername)) {
                    purchaseRecords.add(username);
                    purchaseRecords.add(subscription);
                    purchaseRecords.add(price);
                    found = true;
                }
            }

            if (!found) {
                System.out.println("No records found for username: " + targetUsername);
            }
        } catch (IOException e) {
            System.out.println("An error occurred while reading the purchase history file.");
            e.printStackTrace();
        }

        return purchaseRecords;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        PurchaseButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        GiftButton = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Purchasing Subscription");

        PurchaseButton.setText("Purchase");
        PurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("or");

        jLabel3.setText("Gift to other user:");

        GiftButton.setText("Gift");
        GiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiftButtonActionPerformed(evt);
            }
        });

        ErrorLabel.setText("Not enough funds");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UsernameField)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PurchaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GiftButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(ErrorLabel)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GiftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ErrorLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Subscription updateSubscription(Subscription user) {
    switch(type) {
        case "youtube":
            user.setYoutubeSubscription(true);
            user.setCredits(user.getCredits() - 400);
            return user;
        case "netflix":
            user.setNetflixSubscription(true);
            user.setCredits(user.getCredits() - 600);
            return user;
        case "spotify":
            user.setSpotifySubscription(true);
            user.setCredits(user.getCredits() - 200);
            return user;
        case "amazon":
            user.setAmazonSubscription(true);
            user.setCredits(user.getCredits() - 300);
            return user;
        case "foodpanda":
            user.setFoodpandaSubscription(true);
            user.setCredits(user.getCredits() - 150);
            return user;
        case "hbo":
            user.setHbomaxSubscription(true);
            user.setCredits(user.getCredits() - 500);
            return user;
        case "hulu":
            user.setHuluSubscription(true);
            user.setCredits(user.getCredits() - 450);
            return user;
        case "crunchyroll":
            user.setCrunchyrollSubscription(true);
            user.setCredits(user.getCredits() - 360);
            return user;
        default:
            throw new IllegalArgumentException("Unknown subscription type: " + type);
    }
}
    
    private boolean checkForFunds(){
        if (this.price > this.userData.getCredits() ) {
            ErrorLabel.setText("Not enough Funds");
            ErrorLabel.setVisible(true);
            return false;
        } else {
            return true;
        }
    }
    
    private void GiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiftButtonActionPerformed
        if (checkForFunds()) {
            Login userToGet = new Login();
            try {
                Subscription newUser = userToGet.fetchAllUserData(UsernameField.getText());
                newUser = updateSubscription(newUser);
                newUser.writeClassToFile();
                newUser.writePurchaseHistory(type, price);
            
                setVisible(false);
            } catch (Exception ex) {
                
                ErrorLabel.setText("username not found");
                ErrorLabel.setVisible(true);
            };
            
        }
    }//GEN-LAST:event_GiftButtonActionPerformed

    private void PurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseButtonActionPerformed
        if (checkForFunds()) {
            updateSubscription(this.userData);
            userData.writeClassToFile();
            setVisible(false);
            userData.writePurchaseHistory(type, price);
        }
    }//GEN-LAST:event_PurchaseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuySubscriptionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuySubscriptionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuySubscriptionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuySubscriptionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuySubscriptionDialog dialog = new BuySubscriptionDialog(new javax.swing.JFrame(), true, userData, type, price);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JButton GiftButton;
    private javax.swing.JButton PurchaseButton;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
